package cn.windy.module.examination.mybatis.model;

public class DisRate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_rate.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_rate.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_rate.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_rate.rate_value
     *
     * @mbggenerated
     */
    private Float rateValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_rate.rate_describe
     *
     * @mbggenerated
     */
    private String rateDescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_rate.attr0
     *
     * @mbggenerated
     */
    private String attr0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_rate.attr1
     *
     * @mbggenerated
     */
    private String attr1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_rate.attr2
     *
     * @mbggenerated
     */
    private String attr2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_rate.attr3
     *
     * @mbggenerated
     */
    private String attr3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_rate.attr4
     *
     * @mbggenerated
     */
    private String attr4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_rate.attr5
     *
     * @mbggenerated
     */
    private String attr5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_rate.attr6
     *
     * @mbggenerated
     */
    private String attr6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_rate.attr7
     *
     * @mbggenerated
     */
    private String attr7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_rate.attr8
     *
     * @mbggenerated
     */
    private String attr8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_rate.attr9
     *
     * @mbggenerated
     */
    private String attr9;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_rate.id
     *
     * @return the value of dis_rate.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_rate.id
     *
     * @param id the value for dis_rate.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_rate.name
     *
     * @return the value of dis_rate.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_rate.name
     *
     * @param name the value for dis_rate.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_rate.type
     *
     * @return the value of dis_rate.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_rate.type
     *
     * @param type the value for dis_rate.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_rate.rate_value
     *
     * @return the value of dis_rate.rate_value
     *
     * @mbggenerated
     */
    public Float getRateValue() {
        return rateValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_rate.rate_value
     *
     * @param rateValue the value for dis_rate.rate_value
     *
     * @mbggenerated
     */
    public void setRateValue(Float rateValue) {
        this.rateValue = rateValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_rate.rate_describe
     *
     * @return the value of dis_rate.rate_describe
     *
     * @mbggenerated
     */
    public String getRateDescribe() {
        return rateDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_rate.rate_describe
     *
     * @param rateDescribe the value for dis_rate.rate_describe
     *
     * @mbggenerated
     */
    public void setRateDescribe(String rateDescribe) {
        this.rateDescribe = rateDescribe == null ? null : rateDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_rate.attr0
     *
     * @return the value of dis_rate.attr0
     *
     * @mbggenerated
     */
    public String getAttr0() {
        return attr0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_rate.attr0
     *
     * @param attr0 the value for dis_rate.attr0
     *
     * @mbggenerated
     */
    public void setAttr0(String attr0) {
        this.attr0 = attr0 == null ? null : attr0.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_rate.attr1
     *
     * @return the value of dis_rate.attr1
     *
     * @mbggenerated
     */
    public String getAttr1() {
        return attr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_rate.attr1
     *
     * @param attr1 the value for dis_rate.attr1
     *
     * @mbggenerated
     */
    public void setAttr1(String attr1) {
        this.attr1 = attr1 == null ? null : attr1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_rate.attr2
     *
     * @return the value of dis_rate.attr2
     *
     * @mbggenerated
     */
    public String getAttr2() {
        return attr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_rate.attr2
     *
     * @param attr2 the value for dis_rate.attr2
     *
     * @mbggenerated
     */
    public void setAttr2(String attr2) {
        this.attr2 = attr2 == null ? null : attr2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_rate.attr3
     *
     * @return the value of dis_rate.attr3
     *
     * @mbggenerated
     */
    public String getAttr3() {
        return attr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_rate.attr3
     *
     * @param attr3 the value for dis_rate.attr3
     *
     * @mbggenerated
     */
    public void setAttr3(String attr3) {
        this.attr3 = attr3 == null ? null : attr3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_rate.attr4
     *
     * @return the value of dis_rate.attr4
     *
     * @mbggenerated
     */
    public String getAttr4() {
        return attr4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_rate.attr4
     *
     * @param attr4 the value for dis_rate.attr4
     *
     * @mbggenerated
     */
    public void setAttr4(String attr4) {
        this.attr4 = attr4 == null ? null : attr4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_rate.attr5
     *
     * @return the value of dis_rate.attr5
     *
     * @mbggenerated
     */
    public String getAttr5() {
        return attr5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_rate.attr5
     *
     * @param attr5 the value for dis_rate.attr5
     *
     * @mbggenerated
     */
    public void setAttr5(String attr5) {
        this.attr5 = attr5 == null ? null : attr5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_rate.attr6
     *
     * @return the value of dis_rate.attr6
     *
     * @mbggenerated
     */
    public String getAttr6() {
        return attr6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_rate.attr6
     *
     * @param attr6 the value for dis_rate.attr6
     *
     * @mbggenerated
     */
    public void setAttr6(String attr6) {
        this.attr6 = attr6 == null ? null : attr6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_rate.attr7
     *
     * @return the value of dis_rate.attr7
     *
     * @mbggenerated
     */
    public String getAttr7() {
        return attr7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_rate.attr7
     *
     * @param attr7 the value for dis_rate.attr7
     *
     * @mbggenerated
     */
    public void setAttr7(String attr7) {
        this.attr7 = attr7 == null ? null : attr7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_rate.attr8
     *
     * @return the value of dis_rate.attr8
     *
     * @mbggenerated
     */
    public String getAttr8() {
        return attr8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_rate.attr8
     *
     * @param attr8 the value for dis_rate.attr8
     *
     * @mbggenerated
     */
    public void setAttr8(String attr8) {
        this.attr8 = attr8 == null ? null : attr8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_rate.attr9
     *
     * @return the value of dis_rate.attr9
     *
     * @mbggenerated
     */
    public String getAttr9() {
        return attr9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_rate.attr9
     *
     * @param attr9 the value for dis_rate.attr9
     *
     * @mbggenerated
     */
    public void setAttr9(String attr9) {
        this.attr9 = attr9 == null ? null : attr9.trim();
    }
}