package cn.windy.module.examination.mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class DisRelationshipQuery {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dis_relationship
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dis_relationship
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dis_relationship
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_relationship
     *
     * @mbggenerated
     */
    public DisRelationshipQuery() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_relationship
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_relationship
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_relationship
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_relationship
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_relationship
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_relationship
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_relationship
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_relationship
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_relationship
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_relationship
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dis_relationship
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andMarkIsNull() {
            addCriterion("mark is null");
            return (Criteria) this;
        }

        public Criteria andMarkIsNotNull() {
            addCriterion("mark is not null");
            return (Criteria) this;
        }

        public Criteria andMarkEqualTo(Integer value) {
            addCriterion("mark =", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkNotEqualTo(Integer value) {
            addCriterion("mark <>", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkGreaterThan(Integer value) {
            addCriterion("mark >", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkGreaterThanOrEqualTo(Integer value) {
            addCriterion("mark >=", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkLessThan(Integer value) {
            addCriterion("mark <", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkLessThanOrEqualTo(Integer value) {
            addCriterion("mark <=", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkIn(List<Integer> values) {
            addCriterion("mark in", values, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkNotIn(List<Integer> values) {
            addCriterion("mark not in", values, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkBetween(Integer value1, Integer value2) {
            addCriterion("mark between", value1, value2, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkNotBetween(Integer value1, Integer value2) {
            addCriterion("mark not between", value1, value2, "mark");
            return (Criteria) this;
        }

        public Criteria andPMarkIsNull() {
            addCriterion("p_mark is null");
            return (Criteria) this;
        }

        public Criteria andPMarkIsNotNull() {
            addCriterion("p_mark is not null");
            return (Criteria) this;
        }

        public Criteria andPMarkEqualTo(Integer value) {
            addCriterion("p_mark =", value, "pMark");
            return (Criteria) this;
        }

        public Criteria andPMarkNotEqualTo(Integer value) {
            addCriterion("p_mark <>", value, "pMark");
            return (Criteria) this;
        }

        public Criteria andPMarkGreaterThan(Integer value) {
            addCriterion("p_mark >", value, "pMark");
            return (Criteria) this;
        }

        public Criteria andPMarkGreaterThanOrEqualTo(Integer value) {
            addCriterion("p_mark >=", value, "pMark");
            return (Criteria) this;
        }

        public Criteria andPMarkLessThan(Integer value) {
            addCriterion("p_mark <", value, "pMark");
            return (Criteria) this;
        }

        public Criteria andPMarkLessThanOrEqualTo(Integer value) {
            addCriterion("p_mark <=", value, "pMark");
            return (Criteria) this;
        }

        public Criteria andPMarkIn(List<Integer> values) {
            addCriterion("p_mark in", values, "pMark");
            return (Criteria) this;
        }

        public Criteria andPMarkNotIn(List<Integer> values) {
            addCriterion("p_mark not in", values, "pMark");
            return (Criteria) this;
        }

        public Criteria andPMarkBetween(Integer value1, Integer value2) {
            addCriterion("p_mark between", value1, value2, "pMark");
            return (Criteria) this;
        }

        public Criteria andPMarkNotBetween(Integer value1, Integer value2) {
            addCriterion("p_mark not between", value1, value2, "pMark");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andShipDescribeIsNull() {
            addCriterion("ship_describe is null");
            return (Criteria) this;
        }

        public Criteria andShipDescribeIsNotNull() {
            addCriterion("ship_describe is not null");
            return (Criteria) this;
        }

        public Criteria andShipDescribeEqualTo(String value) {
            addCriterion("ship_describe =", value, "shipDescribe");
            return (Criteria) this;
        }

        public Criteria andShipDescribeNotEqualTo(String value) {
            addCriterion("ship_describe <>", value, "shipDescribe");
            return (Criteria) this;
        }

        public Criteria andShipDescribeGreaterThan(String value) {
            addCriterion("ship_describe >", value, "shipDescribe");
            return (Criteria) this;
        }

        public Criteria andShipDescribeGreaterThanOrEqualTo(String value) {
            addCriterion("ship_describe >=", value, "shipDescribe");
            return (Criteria) this;
        }

        public Criteria andShipDescribeLessThan(String value) {
            addCriterion("ship_describe <", value, "shipDescribe");
            return (Criteria) this;
        }

        public Criteria andShipDescribeLessThanOrEqualTo(String value) {
            addCriterion("ship_describe <=", value, "shipDescribe");
            return (Criteria) this;
        }

        public Criteria andShipDescribeLike(String value) {
            addCriterion("ship_describe like", value, "shipDescribe");
            return (Criteria) this;
        }

        public Criteria andShipDescribeNotLike(String value) {
            addCriterion("ship_describe not like", value, "shipDescribe");
            return (Criteria) this;
        }

        public Criteria andShipDescribeIn(List<String> values) {
            addCriterion("ship_describe in", values, "shipDescribe");
            return (Criteria) this;
        }

        public Criteria andShipDescribeNotIn(List<String> values) {
            addCriterion("ship_describe not in", values, "shipDescribe");
            return (Criteria) this;
        }

        public Criteria andShipDescribeBetween(String value1, String value2) {
            addCriterion("ship_describe between", value1, value2, "shipDescribe");
            return (Criteria) this;
        }

        public Criteria andShipDescribeNotBetween(String value1, String value2) {
            addCriterion("ship_describe not between", value1, value2, "shipDescribe");
            return (Criteria) this;
        }

        public Criteria andArrt0IsNull() {
            addCriterion("arrt0 is null");
            return (Criteria) this;
        }

        public Criteria andArrt0IsNotNull() {
            addCriterion("arrt0 is not null");
            return (Criteria) this;
        }

        public Criteria andArrt0EqualTo(String value) {
            addCriterion("arrt0 =", value, "arrt0");
            return (Criteria) this;
        }

        public Criteria andArrt0NotEqualTo(String value) {
            addCriterion("arrt0 <>", value, "arrt0");
            return (Criteria) this;
        }

        public Criteria andArrt0GreaterThan(String value) {
            addCriterion("arrt0 >", value, "arrt0");
            return (Criteria) this;
        }

        public Criteria andArrt0GreaterThanOrEqualTo(String value) {
            addCriterion("arrt0 >=", value, "arrt0");
            return (Criteria) this;
        }

        public Criteria andArrt0LessThan(String value) {
            addCriterion("arrt0 <", value, "arrt0");
            return (Criteria) this;
        }

        public Criteria andArrt0LessThanOrEqualTo(String value) {
            addCriterion("arrt0 <=", value, "arrt0");
            return (Criteria) this;
        }

        public Criteria andArrt0Like(String value) {
            addCriterion("arrt0 like", value, "arrt0");
            return (Criteria) this;
        }

        public Criteria andArrt0NotLike(String value) {
            addCriterion("arrt0 not like", value, "arrt0");
            return (Criteria) this;
        }

        public Criteria andArrt0In(List<String> values) {
            addCriterion("arrt0 in", values, "arrt0");
            return (Criteria) this;
        }

        public Criteria andArrt0NotIn(List<String> values) {
            addCriterion("arrt0 not in", values, "arrt0");
            return (Criteria) this;
        }

        public Criteria andArrt0Between(String value1, String value2) {
            addCriterion("arrt0 between", value1, value2, "arrt0");
            return (Criteria) this;
        }

        public Criteria andArrt0NotBetween(String value1, String value2) {
            addCriterion("arrt0 not between", value1, value2, "arrt0");
            return (Criteria) this;
        }

        public Criteria andArrt1IsNull() {
            addCriterion("arrt1 is null");
            return (Criteria) this;
        }

        public Criteria andArrt1IsNotNull() {
            addCriterion("arrt1 is not null");
            return (Criteria) this;
        }

        public Criteria andArrt1EqualTo(String value) {
            addCriterion("arrt1 =", value, "arrt1");
            return (Criteria) this;
        }

        public Criteria andArrt1NotEqualTo(String value) {
            addCriterion("arrt1 <>", value, "arrt1");
            return (Criteria) this;
        }

        public Criteria andArrt1GreaterThan(String value) {
            addCriterion("arrt1 >", value, "arrt1");
            return (Criteria) this;
        }

        public Criteria andArrt1GreaterThanOrEqualTo(String value) {
            addCriterion("arrt1 >=", value, "arrt1");
            return (Criteria) this;
        }

        public Criteria andArrt1LessThan(String value) {
            addCriterion("arrt1 <", value, "arrt1");
            return (Criteria) this;
        }

        public Criteria andArrt1LessThanOrEqualTo(String value) {
            addCriterion("arrt1 <=", value, "arrt1");
            return (Criteria) this;
        }

        public Criteria andArrt1Like(String value) {
            addCriterion("arrt1 like", value, "arrt1");
            return (Criteria) this;
        }

        public Criteria andArrt1NotLike(String value) {
            addCriterion("arrt1 not like", value, "arrt1");
            return (Criteria) this;
        }

        public Criteria andArrt1In(List<String> values) {
            addCriterion("arrt1 in", values, "arrt1");
            return (Criteria) this;
        }

        public Criteria andArrt1NotIn(List<String> values) {
            addCriterion("arrt1 not in", values, "arrt1");
            return (Criteria) this;
        }

        public Criteria andArrt1Between(String value1, String value2) {
            addCriterion("arrt1 between", value1, value2, "arrt1");
            return (Criteria) this;
        }

        public Criteria andArrt1NotBetween(String value1, String value2) {
            addCriterion("arrt1 not between", value1, value2, "arrt1");
            return (Criteria) this;
        }

        public Criteria andArrt2IsNull() {
            addCriterion("arrt2 is null");
            return (Criteria) this;
        }

        public Criteria andArrt2IsNotNull() {
            addCriterion("arrt2 is not null");
            return (Criteria) this;
        }

        public Criteria andArrt2EqualTo(String value) {
            addCriterion("arrt2 =", value, "arrt2");
            return (Criteria) this;
        }

        public Criteria andArrt2NotEqualTo(String value) {
            addCriterion("arrt2 <>", value, "arrt2");
            return (Criteria) this;
        }

        public Criteria andArrt2GreaterThan(String value) {
            addCriterion("arrt2 >", value, "arrt2");
            return (Criteria) this;
        }

        public Criteria andArrt2GreaterThanOrEqualTo(String value) {
            addCriterion("arrt2 >=", value, "arrt2");
            return (Criteria) this;
        }

        public Criteria andArrt2LessThan(String value) {
            addCriterion("arrt2 <", value, "arrt2");
            return (Criteria) this;
        }

        public Criteria andArrt2LessThanOrEqualTo(String value) {
            addCriterion("arrt2 <=", value, "arrt2");
            return (Criteria) this;
        }

        public Criteria andArrt2Like(String value) {
            addCriterion("arrt2 like", value, "arrt2");
            return (Criteria) this;
        }

        public Criteria andArrt2NotLike(String value) {
            addCriterion("arrt2 not like", value, "arrt2");
            return (Criteria) this;
        }

        public Criteria andArrt2In(List<String> values) {
            addCriterion("arrt2 in", values, "arrt2");
            return (Criteria) this;
        }

        public Criteria andArrt2NotIn(List<String> values) {
            addCriterion("arrt2 not in", values, "arrt2");
            return (Criteria) this;
        }

        public Criteria andArrt2Between(String value1, String value2) {
            addCriterion("arrt2 between", value1, value2, "arrt2");
            return (Criteria) this;
        }

        public Criteria andArrt2NotBetween(String value1, String value2) {
            addCriterion("arrt2 not between", value1, value2, "arrt2");
            return (Criteria) this;
        }

        public Criteria andArrt3IsNull() {
            addCriterion("arrt3 is null");
            return (Criteria) this;
        }

        public Criteria andArrt3IsNotNull() {
            addCriterion("arrt3 is not null");
            return (Criteria) this;
        }

        public Criteria andArrt3EqualTo(String value) {
            addCriterion("arrt3 =", value, "arrt3");
            return (Criteria) this;
        }

        public Criteria andArrt3NotEqualTo(String value) {
            addCriterion("arrt3 <>", value, "arrt3");
            return (Criteria) this;
        }

        public Criteria andArrt3GreaterThan(String value) {
            addCriterion("arrt3 >", value, "arrt3");
            return (Criteria) this;
        }

        public Criteria andArrt3GreaterThanOrEqualTo(String value) {
            addCriterion("arrt3 >=", value, "arrt3");
            return (Criteria) this;
        }

        public Criteria andArrt3LessThan(String value) {
            addCriterion("arrt3 <", value, "arrt3");
            return (Criteria) this;
        }

        public Criteria andArrt3LessThanOrEqualTo(String value) {
            addCriterion("arrt3 <=", value, "arrt3");
            return (Criteria) this;
        }

        public Criteria andArrt3Like(String value) {
            addCriterion("arrt3 like", value, "arrt3");
            return (Criteria) this;
        }

        public Criteria andArrt3NotLike(String value) {
            addCriterion("arrt3 not like", value, "arrt3");
            return (Criteria) this;
        }

        public Criteria andArrt3In(List<String> values) {
            addCriterion("arrt3 in", values, "arrt3");
            return (Criteria) this;
        }

        public Criteria andArrt3NotIn(List<String> values) {
            addCriterion("arrt3 not in", values, "arrt3");
            return (Criteria) this;
        }

        public Criteria andArrt3Between(String value1, String value2) {
            addCriterion("arrt3 between", value1, value2, "arrt3");
            return (Criteria) this;
        }

        public Criteria andArrt3NotBetween(String value1, String value2) {
            addCriterion("arrt3 not between", value1, value2, "arrt3");
            return (Criteria) this;
        }

        public Criteria andArrt4IsNull() {
            addCriterion("arrt4 is null");
            return (Criteria) this;
        }

        public Criteria andArrt4IsNotNull() {
            addCriterion("arrt4 is not null");
            return (Criteria) this;
        }

        public Criteria andArrt4EqualTo(String value) {
            addCriterion("arrt4 =", value, "arrt4");
            return (Criteria) this;
        }

        public Criteria andArrt4NotEqualTo(String value) {
            addCriterion("arrt4 <>", value, "arrt4");
            return (Criteria) this;
        }

        public Criteria andArrt4GreaterThan(String value) {
            addCriterion("arrt4 >", value, "arrt4");
            return (Criteria) this;
        }

        public Criteria andArrt4GreaterThanOrEqualTo(String value) {
            addCriterion("arrt4 >=", value, "arrt4");
            return (Criteria) this;
        }

        public Criteria andArrt4LessThan(String value) {
            addCriterion("arrt4 <", value, "arrt4");
            return (Criteria) this;
        }

        public Criteria andArrt4LessThanOrEqualTo(String value) {
            addCriterion("arrt4 <=", value, "arrt4");
            return (Criteria) this;
        }

        public Criteria andArrt4Like(String value) {
            addCriterion("arrt4 like", value, "arrt4");
            return (Criteria) this;
        }

        public Criteria andArrt4NotLike(String value) {
            addCriterion("arrt4 not like", value, "arrt4");
            return (Criteria) this;
        }

        public Criteria andArrt4In(List<String> values) {
            addCriterion("arrt4 in", values, "arrt4");
            return (Criteria) this;
        }

        public Criteria andArrt4NotIn(List<String> values) {
            addCriterion("arrt4 not in", values, "arrt4");
            return (Criteria) this;
        }

        public Criteria andArrt4Between(String value1, String value2) {
            addCriterion("arrt4 between", value1, value2, "arrt4");
            return (Criteria) this;
        }

        public Criteria andArrt4NotBetween(String value1, String value2) {
            addCriterion("arrt4 not between", value1, value2, "arrt4");
            return (Criteria) this;
        }

        public Criteria andArrt5IsNull() {
            addCriterion("arrt5 is null");
            return (Criteria) this;
        }

        public Criteria andArrt5IsNotNull() {
            addCriterion("arrt5 is not null");
            return (Criteria) this;
        }

        public Criteria andArrt5EqualTo(String value) {
            addCriterion("arrt5 =", value, "arrt5");
            return (Criteria) this;
        }

        public Criteria andArrt5NotEqualTo(String value) {
            addCriterion("arrt5 <>", value, "arrt5");
            return (Criteria) this;
        }

        public Criteria andArrt5GreaterThan(String value) {
            addCriterion("arrt5 >", value, "arrt5");
            return (Criteria) this;
        }

        public Criteria andArrt5GreaterThanOrEqualTo(String value) {
            addCriterion("arrt5 >=", value, "arrt5");
            return (Criteria) this;
        }

        public Criteria andArrt5LessThan(String value) {
            addCriterion("arrt5 <", value, "arrt5");
            return (Criteria) this;
        }

        public Criteria andArrt5LessThanOrEqualTo(String value) {
            addCriterion("arrt5 <=", value, "arrt5");
            return (Criteria) this;
        }

        public Criteria andArrt5Like(String value) {
            addCriterion("arrt5 like", value, "arrt5");
            return (Criteria) this;
        }

        public Criteria andArrt5NotLike(String value) {
            addCriterion("arrt5 not like", value, "arrt5");
            return (Criteria) this;
        }

        public Criteria andArrt5In(List<String> values) {
            addCriterion("arrt5 in", values, "arrt5");
            return (Criteria) this;
        }

        public Criteria andArrt5NotIn(List<String> values) {
            addCriterion("arrt5 not in", values, "arrt5");
            return (Criteria) this;
        }

        public Criteria andArrt5Between(String value1, String value2) {
            addCriterion("arrt5 between", value1, value2, "arrt5");
            return (Criteria) this;
        }

        public Criteria andArrt5NotBetween(String value1, String value2) {
            addCriterion("arrt5 not between", value1, value2, "arrt5");
            return (Criteria) this;
        }

        public Criteria andArrt6IsNull() {
            addCriterion("arrt6 is null");
            return (Criteria) this;
        }

        public Criteria andArrt6IsNotNull() {
            addCriterion("arrt6 is not null");
            return (Criteria) this;
        }

        public Criteria andArrt6EqualTo(String value) {
            addCriterion("arrt6 =", value, "arrt6");
            return (Criteria) this;
        }

        public Criteria andArrt6NotEqualTo(String value) {
            addCriterion("arrt6 <>", value, "arrt6");
            return (Criteria) this;
        }

        public Criteria andArrt6GreaterThan(String value) {
            addCriterion("arrt6 >", value, "arrt6");
            return (Criteria) this;
        }

        public Criteria andArrt6GreaterThanOrEqualTo(String value) {
            addCriterion("arrt6 >=", value, "arrt6");
            return (Criteria) this;
        }

        public Criteria andArrt6LessThan(String value) {
            addCriterion("arrt6 <", value, "arrt6");
            return (Criteria) this;
        }

        public Criteria andArrt6LessThanOrEqualTo(String value) {
            addCriterion("arrt6 <=", value, "arrt6");
            return (Criteria) this;
        }

        public Criteria andArrt6Like(String value) {
            addCriterion("arrt6 like", value, "arrt6");
            return (Criteria) this;
        }

        public Criteria andArrt6NotLike(String value) {
            addCriterion("arrt6 not like", value, "arrt6");
            return (Criteria) this;
        }

        public Criteria andArrt6In(List<String> values) {
            addCriterion("arrt6 in", values, "arrt6");
            return (Criteria) this;
        }

        public Criteria andArrt6NotIn(List<String> values) {
            addCriterion("arrt6 not in", values, "arrt6");
            return (Criteria) this;
        }

        public Criteria andArrt6Between(String value1, String value2) {
            addCriterion("arrt6 between", value1, value2, "arrt6");
            return (Criteria) this;
        }

        public Criteria andArrt6NotBetween(String value1, String value2) {
            addCriterion("arrt6 not between", value1, value2, "arrt6");
            return (Criteria) this;
        }

        public Criteria andArrt7IsNull() {
            addCriterion("arrt7 is null");
            return (Criteria) this;
        }

        public Criteria andArrt7IsNotNull() {
            addCriterion("arrt7 is not null");
            return (Criteria) this;
        }

        public Criteria andArrt7EqualTo(String value) {
            addCriterion("arrt7 =", value, "arrt7");
            return (Criteria) this;
        }

        public Criteria andArrt7NotEqualTo(String value) {
            addCriterion("arrt7 <>", value, "arrt7");
            return (Criteria) this;
        }

        public Criteria andArrt7GreaterThan(String value) {
            addCriterion("arrt7 >", value, "arrt7");
            return (Criteria) this;
        }

        public Criteria andArrt7GreaterThanOrEqualTo(String value) {
            addCriterion("arrt7 >=", value, "arrt7");
            return (Criteria) this;
        }

        public Criteria andArrt7LessThan(String value) {
            addCriterion("arrt7 <", value, "arrt7");
            return (Criteria) this;
        }

        public Criteria andArrt7LessThanOrEqualTo(String value) {
            addCriterion("arrt7 <=", value, "arrt7");
            return (Criteria) this;
        }

        public Criteria andArrt7Like(String value) {
            addCriterion("arrt7 like", value, "arrt7");
            return (Criteria) this;
        }

        public Criteria andArrt7NotLike(String value) {
            addCriterion("arrt7 not like", value, "arrt7");
            return (Criteria) this;
        }

        public Criteria andArrt7In(List<String> values) {
            addCriterion("arrt7 in", values, "arrt7");
            return (Criteria) this;
        }

        public Criteria andArrt7NotIn(List<String> values) {
            addCriterion("arrt7 not in", values, "arrt7");
            return (Criteria) this;
        }

        public Criteria andArrt7Between(String value1, String value2) {
            addCriterion("arrt7 between", value1, value2, "arrt7");
            return (Criteria) this;
        }

        public Criteria andArrt7NotBetween(String value1, String value2) {
            addCriterion("arrt7 not between", value1, value2, "arrt7");
            return (Criteria) this;
        }

        public Criteria andArrt8IsNull() {
            addCriterion("arrt8 is null");
            return (Criteria) this;
        }

        public Criteria andArrt8IsNotNull() {
            addCriterion("arrt8 is not null");
            return (Criteria) this;
        }

        public Criteria andArrt8EqualTo(String value) {
            addCriterion("arrt8 =", value, "arrt8");
            return (Criteria) this;
        }

        public Criteria andArrt8NotEqualTo(String value) {
            addCriterion("arrt8 <>", value, "arrt8");
            return (Criteria) this;
        }

        public Criteria andArrt8GreaterThan(String value) {
            addCriterion("arrt8 >", value, "arrt8");
            return (Criteria) this;
        }

        public Criteria andArrt8GreaterThanOrEqualTo(String value) {
            addCriterion("arrt8 >=", value, "arrt8");
            return (Criteria) this;
        }

        public Criteria andArrt8LessThan(String value) {
            addCriterion("arrt8 <", value, "arrt8");
            return (Criteria) this;
        }

        public Criteria andArrt8LessThanOrEqualTo(String value) {
            addCriterion("arrt8 <=", value, "arrt8");
            return (Criteria) this;
        }

        public Criteria andArrt8Like(String value) {
            addCriterion("arrt8 like", value, "arrt8");
            return (Criteria) this;
        }

        public Criteria andArrt8NotLike(String value) {
            addCriterion("arrt8 not like", value, "arrt8");
            return (Criteria) this;
        }

        public Criteria andArrt8In(List<String> values) {
            addCriterion("arrt8 in", values, "arrt8");
            return (Criteria) this;
        }

        public Criteria andArrt8NotIn(List<String> values) {
            addCriterion("arrt8 not in", values, "arrt8");
            return (Criteria) this;
        }

        public Criteria andArrt8Between(String value1, String value2) {
            addCriterion("arrt8 between", value1, value2, "arrt8");
            return (Criteria) this;
        }

        public Criteria andArrt8NotBetween(String value1, String value2) {
            addCriterion("arrt8 not between", value1, value2, "arrt8");
            return (Criteria) this;
        }

        public Criteria andArrt9IsNull() {
            addCriterion("arrt9 is null");
            return (Criteria) this;
        }

        public Criteria andArrt9IsNotNull() {
            addCriterion("arrt9 is not null");
            return (Criteria) this;
        }

        public Criteria andArrt9EqualTo(String value) {
            addCriterion("arrt9 =", value, "arrt9");
            return (Criteria) this;
        }

        public Criteria andArrt9NotEqualTo(String value) {
            addCriterion("arrt9 <>", value, "arrt9");
            return (Criteria) this;
        }

        public Criteria andArrt9GreaterThan(String value) {
            addCriterion("arrt9 >", value, "arrt9");
            return (Criteria) this;
        }

        public Criteria andArrt9GreaterThanOrEqualTo(String value) {
            addCriterion("arrt9 >=", value, "arrt9");
            return (Criteria) this;
        }

        public Criteria andArrt9LessThan(String value) {
            addCriterion("arrt9 <", value, "arrt9");
            return (Criteria) this;
        }

        public Criteria andArrt9LessThanOrEqualTo(String value) {
            addCriterion("arrt9 <=", value, "arrt9");
            return (Criteria) this;
        }

        public Criteria andArrt9Like(String value) {
            addCriterion("arrt9 like", value, "arrt9");
            return (Criteria) this;
        }

        public Criteria andArrt9NotLike(String value) {
            addCriterion("arrt9 not like", value, "arrt9");
            return (Criteria) this;
        }

        public Criteria andArrt9In(List<String> values) {
            addCriterion("arrt9 in", values, "arrt9");
            return (Criteria) this;
        }

        public Criteria andArrt9NotIn(List<String> values) {
            addCriterion("arrt9 not in", values, "arrt9");
            return (Criteria) this;
        }

        public Criteria andArrt9Between(String value1, String value2) {
            addCriterion("arrt9 between", value1, value2, "arrt9");
            return (Criteria) this;
        }

        public Criteria andArrt9NotBetween(String value1, String value2) {
            addCriterion("arrt9 not between", value1, value2, "arrt9");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dis_relationship
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dis_relationship
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}