package cn.windy.module.examination.mybatis.model;

public class ExamPersonnel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_personnel.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_personnel.exam_id
     *
     * @mbggenerated
     */
    private Long examId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_personnel.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_personnel.creat_id
     *
     * @mbggenerated
     */
    private Long creatId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_personnel.is_exam
     *
     * @mbggenerated
     */
    private Integer isExam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_personnel.is_count
     *
     * @mbggenerated
     */
    private Integer isCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_personnel.attr0
     *
     * @mbggenerated
     */
    private String attr0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_personnel.attr1
     *
     * @mbggenerated
     */
    private String attr1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_personnel.attr2
     *
     * @mbggenerated
     */
    private String attr2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_personnel.attr3
     *
     * @mbggenerated
     */
    private String attr3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_personnel.attr4
     *
     * @mbggenerated
     */
    private String attr4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_personnel.attr5
     *
     * @mbggenerated
     */
    private String attr5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_personnel.attr6
     *
     * @mbggenerated
     */
    private Integer attr6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_personnel.attr7
     *
     * @mbggenerated
     */
    private Integer attr7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_personnel.attr8
     *
     * @mbggenerated
     */
    private Long attr8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_personnel.attr9
     *
     * @mbggenerated
     */
    private Long attr9;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_personnel.id
     *
     * @return the value of exam_personnel.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_personnel.id
     *
     * @param id the value for exam_personnel.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_personnel.exam_id
     *
     * @return the value of exam_personnel.exam_id
     *
     * @mbggenerated
     */
    public Long getExamId() {
        return examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_personnel.exam_id
     *
     * @param examId the value for exam_personnel.exam_id
     *
     * @mbggenerated
     */
    public void setExamId(Long examId) {
        this.examId = examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_personnel.user_id
     *
     * @return the value of exam_personnel.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_personnel.user_id
     *
     * @param userId the value for exam_personnel.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_personnel.creat_id
     *
     * @return the value of exam_personnel.creat_id
     *
     * @mbggenerated
     */
    public Long getCreatId() {
        return creatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_personnel.creat_id
     *
     * @param creatId the value for exam_personnel.creat_id
     *
     * @mbggenerated
     */
    public void setCreatId(Long creatId) {
        this.creatId = creatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_personnel.is_exam
     *
     * @return the value of exam_personnel.is_exam
     *
     * @mbggenerated
     */
    public Integer getIsExam() {
        return isExam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_personnel.is_exam
     *
     * @param isExam the value for exam_personnel.is_exam
     *
     * @mbggenerated
     */
    public void setIsExam(Integer isExam) {
        this.isExam = isExam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_personnel.is_count
     *
     * @return the value of exam_personnel.is_count
     *
     * @mbggenerated
     */
    public Integer getIsCount() {
        return isCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_personnel.is_count
     *
     * @param isCount the value for exam_personnel.is_count
     *
     * @mbggenerated
     */
    public void setIsCount(Integer isCount) {
        this.isCount = isCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_personnel.attr0
     *
     * @return the value of exam_personnel.attr0
     *
     * @mbggenerated
     */
    public String getAttr0() {
        return attr0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_personnel.attr0
     *
     * @param attr0 the value for exam_personnel.attr0
     *
     * @mbggenerated
     */
    public void setAttr0(String attr0) {
        this.attr0 = attr0 == null ? null : attr0.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_personnel.attr1
     *
     * @return the value of exam_personnel.attr1
     *
     * @mbggenerated
     */
    public String getAttr1() {
        return attr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_personnel.attr1
     *
     * @param attr1 the value for exam_personnel.attr1
     *
     * @mbggenerated
     */
    public void setAttr1(String attr1) {
        this.attr1 = attr1 == null ? null : attr1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_personnel.attr2
     *
     * @return the value of exam_personnel.attr2
     *
     * @mbggenerated
     */
    public String getAttr2() {
        return attr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_personnel.attr2
     *
     * @param attr2 the value for exam_personnel.attr2
     *
     * @mbggenerated
     */
    public void setAttr2(String attr2) {
        this.attr2 = attr2 == null ? null : attr2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_personnel.attr3
     *
     * @return the value of exam_personnel.attr3
     *
     * @mbggenerated
     */
    public String getAttr3() {
        return attr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_personnel.attr3
     *
     * @param attr3 the value for exam_personnel.attr3
     *
     * @mbggenerated
     */
    public void setAttr3(String attr3) {
        this.attr3 = attr3 == null ? null : attr3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_personnel.attr4
     *
     * @return the value of exam_personnel.attr4
     *
     * @mbggenerated
     */
    public String getAttr4() {
        return attr4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_personnel.attr4
     *
     * @param attr4 the value for exam_personnel.attr4
     *
     * @mbggenerated
     */
    public void setAttr4(String attr4) {
        this.attr4 = attr4 == null ? null : attr4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_personnel.attr5
     *
     * @return the value of exam_personnel.attr5
     *
     * @mbggenerated
     */
    public String getAttr5() {
        return attr5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_personnel.attr5
     *
     * @param attr5 the value for exam_personnel.attr5
     *
     * @mbggenerated
     */
    public void setAttr5(String attr5) {
        this.attr5 = attr5 == null ? null : attr5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_personnel.attr6
     *
     * @return the value of exam_personnel.attr6
     *
     * @mbggenerated
     */
    public Integer getAttr6() {
        return attr6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_personnel.attr6
     *
     * @param attr6 the value for exam_personnel.attr6
     *
     * @mbggenerated
     */
    public void setAttr6(Integer attr6) {
        this.attr6 = attr6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_personnel.attr7
     *
     * @return the value of exam_personnel.attr7
     *
     * @mbggenerated
     */
    public Integer getAttr7() {
        return attr7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_personnel.attr7
     *
     * @param attr7 the value for exam_personnel.attr7
     *
     * @mbggenerated
     */
    public void setAttr7(Integer attr7) {
        this.attr7 = attr7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_personnel.attr8
     *
     * @return the value of exam_personnel.attr8
     *
     * @mbggenerated
     */
    public Long getAttr8() {
        return attr8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_personnel.attr8
     *
     * @param attr8 the value for exam_personnel.attr8
     *
     * @mbggenerated
     */
    public void setAttr8(Long attr8) {
        this.attr8 = attr8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_personnel.attr9
     *
     * @return the value of exam_personnel.attr9
     *
     * @mbggenerated
     */
    public Long getAttr9() {
        return attr9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_personnel.attr9
     *
     * @param attr9 the value for exam_personnel.attr9
     *
     * @mbggenerated
     */
    public void setAttr9(Long attr9) {
        this.attr9 = attr9;
    }
}