package cn.windy.module.examination.mybatis.model;

public class DisRelationship {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_relationship.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_relationship.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_relationship.mark
     *
     * @mbggenerated
     */
    private Integer mark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_relationship.p_mark
     *
     * @mbggenerated
     */
    private Integer pMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_relationship.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_relationship.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_relationship.ship_describe
     *
     * @mbggenerated
     */
    private String shipDescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_relationship.arrt0
     *
     * @mbggenerated
     */
    private String arrt0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_relationship.arrt1
     *
     * @mbggenerated
     */
    private String arrt1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_relationship.arrt2
     *
     * @mbggenerated
     */
    private String arrt2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_relationship.arrt3
     *
     * @mbggenerated
     */
    private String arrt3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_relationship.arrt4
     *
     * @mbggenerated
     */
    private String arrt4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_relationship.arrt5
     *
     * @mbggenerated
     */
    private String arrt5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_relationship.arrt6
     *
     * @mbggenerated
     */
    private String arrt6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_relationship.arrt7
     *
     * @mbggenerated
     */
    private String arrt7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_relationship.arrt8
     *
     * @mbggenerated
     */
    private String arrt8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_relationship.arrt9
     *
     * @mbggenerated
     */
    private String arrt9;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_relationship.id
     *
     * @return the value of dis_relationship.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_relationship.id
     *
     * @param id the value for dis_relationship.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_relationship.user_id
     *
     * @return the value of dis_relationship.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_relationship.user_id
     *
     * @param userId the value for dis_relationship.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_relationship.mark
     *
     * @return the value of dis_relationship.mark
     *
     * @mbggenerated
     */
    public Integer getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_relationship.mark
     *
     * @param mark the value for dis_relationship.mark
     *
     * @mbggenerated
     */
    public void setMark(Integer mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_relationship.p_mark
     *
     * @return the value of dis_relationship.p_mark
     *
     * @mbggenerated
     */
    public Integer getpMark() {
        return pMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_relationship.p_mark
     *
     * @param pMark the value for dis_relationship.p_mark
     *
     * @mbggenerated
     */
    public void setpMark(Integer pMark) {
        this.pMark = pMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_relationship.name
     *
     * @return the value of dis_relationship.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_relationship.name
     *
     * @param name the value for dis_relationship.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_relationship.type
     *
     * @return the value of dis_relationship.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_relationship.type
     *
     * @param type the value for dis_relationship.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_relationship.ship_describe
     *
     * @return the value of dis_relationship.ship_describe
     *
     * @mbggenerated
     */
    public String getShipDescribe() {
        return shipDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_relationship.ship_describe
     *
     * @param shipDescribe the value for dis_relationship.ship_describe
     *
     * @mbggenerated
     */
    public void setShipDescribe(String shipDescribe) {
        this.shipDescribe = shipDescribe == null ? null : shipDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_relationship.arrt0
     *
     * @return the value of dis_relationship.arrt0
     *
     * @mbggenerated
     */
    public String getArrt0() {
        return arrt0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_relationship.arrt0
     *
     * @param arrt0 the value for dis_relationship.arrt0
     *
     * @mbggenerated
     */
    public void setArrt0(String arrt0) {
        this.arrt0 = arrt0 == null ? null : arrt0.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_relationship.arrt1
     *
     * @return the value of dis_relationship.arrt1
     *
     * @mbggenerated
     */
    public String getArrt1() {
        return arrt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_relationship.arrt1
     *
     * @param arrt1 the value for dis_relationship.arrt1
     *
     * @mbggenerated
     */
    public void setArrt1(String arrt1) {
        this.arrt1 = arrt1 == null ? null : arrt1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_relationship.arrt2
     *
     * @return the value of dis_relationship.arrt2
     *
     * @mbggenerated
     */
    public String getArrt2() {
        return arrt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_relationship.arrt2
     *
     * @param arrt2 the value for dis_relationship.arrt2
     *
     * @mbggenerated
     */
    public void setArrt2(String arrt2) {
        this.arrt2 = arrt2 == null ? null : arrt2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_relationship.arrt3
     *
     * @return the value of dis_relationship.arrt3
     *
     * @mbggenerated
     */
    public String getArrt3() {
        return arrt3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_relationship.arrt3
     *
     * @param arrt3 the value for dis_relationship.arrt3
     *
     * @mbggenerated
     */
    public void setArrt3(String arrt3) {
        this.arrt3 = arrt3 == null ? null : arrt3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_relationship.arrt4
     *
     * @return the value of dis_relationship.arrt4
     *
     * @mbggenerated
     */
    public String getArrt4() {
        return arrt4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_relationship.arrt4
     *
     * @param arrt4 the value for dis_relationship.arrt4
     *
     * @mbggenerated
     */
    public void setArrt4(String arrt4) {
        this.arrt4 = arrt4 == null ? null : arrt4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_relationship.arrt5
     *
     * @return the value of dis_relationship.arrt5
     *
     * @mbggenerated
     */
    public String getArrt5() {
        return arrt5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_relationship.arrt5
     *
     * @param arrt5 the value for dis_relationship.arrt5
     *
     * @mbggenerated
     */
    public void setArrt5(String arrt5) {
        this.arrt5 = arrt5 == null ? null : arrt5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_relationship.arrt6
     *
     * @return the value of dis_relationship.arrt6
     *
     * @mbggenerated
     */
    public String getArrt6() {
        return arrt6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_relationship.arrt6
     *
     * @param arrt6 the value for dis_relationship.arrt6
     *
     * @mbggenerated
     */
    public void setArrt6(String arrt6) {
        this.arrt6 = arrt6 == null ? null : arrt6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_relationship.arrt7
     *
     * @return the value of dis_relationship.arrt7
     *
     * @mbggenerated
     */
    public String getArrt7() {
        return arrt7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_relationship.arrt7
     *
     * @param arrt7 the value for dis_relationship.arrt7
     *
     * @mbggenerated
     */
    public void setArrt7(String arrt7) {
        this.arrt7 = arrt7 == null ? null : arrt7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_relationship.arrt8
     *
     * @return the value of dis_relationship.arrt8
     *
     * @mbggenerated
     */
    public String getArrt8() {
        return arrt8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_relationship.arrt8
     *
     * @param arrt8 the value for dis_relationship.arrt8
     *
     * @mbggenerated
     */
    public void setArrt8(String arrt8) {
        this.arrt8 = arrt8 == null ? null : arrt8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_relationship.arrt9
     *
     * @return the value of dis_relationship.arrt9
     *
     * @mbggenerated
     */
    public String getArrt9() {
        return arrt9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_relationship.arrt9
     *
     * @param arrt9 the value for dis_relationship.arrt9
     *
     * @mbggenerated
     */
    public void setArrt9(String arrt9) {
        this.arrt9 = arrt9 == null ? null : arrt9.trim();
    }
}