package cn.windy.module.examination.mybatis.model;

public class Examination {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination.exam_name
     *
     * @mbggenerated
     */
    private String examName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination.creat_id
     *
     * @mbggenerated
     */
    private Long creatId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination.org_id
     *
     * @mbggenerated
     */
    private Long orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination.start_time
     *
     * @mbggenerated
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination.end_time
     *
     * @mbggenerated
     */
    private String endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination.sh_people
     *
     * @mbggenerated
     */
    private Integer shPeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination.ac_people
     *
     * @mbggenerated
     */
    private Integer acPeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination.founder
     *
     * @mbggenerated
     */
    private Long founder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination.exam_status
     *
     * @mbggenerated
     */
    private Integer examStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination.attr0
     *
     * @mbggenerated
     */
    private String attr0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination.attr1
     *
     * @mbggenerated
     */
    private String attr1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination.attr2
     *
     * @mbggenerated
     */
    private String attr2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination.attr3
     *
     * @mbggenerated
     */
    private String attr3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination.attr4
     *
     * @mbggenerated
     */
    private String attr4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination.attr5
     *
     * @mbggenerated
     */
    private String attr5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination.attr6
     *
     * @mbggenerated
     */
    private Integer attr6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination.attr7
     *
     * @mbggenerated
     */
    private Integer attr7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination.attr8
     *
     * @mbggenerated
     */
    private Long attr8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination.attr9
     *
     * @mbggenerated
     */
    private Long attr9;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examination.id
     *
     * @return the value of examination.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examination.id
     *
     * @param id the value for examination.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examination.exam_name
     *
     * @return the value of examination.exam_name
     *
     * @mbggenerated
     */
    public String getExamName() {
        return examName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examination.exam_name
     *
     * @param examName the value for examination.exam_name
     *
     * @mbggenerated
     */
    public void setExamName(String examName) {
        this.examName = examName == null ? null : examName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examination.creat_id
     *
     * @return the value of examination.creat_id
     *
     * @mbggenerated
     */
    public Long getCreatId() {
        return creatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examination.creat_id
     *
     * @param creatId the value for examination.creat_id
     *
     * @mbggenerated
     */
    public void setCreatId(Long creatId) {
        this.creatId = creatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examination.org_id
     *
     * @return the value of examination.org_id
     *
     * @mbggenerated
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examination.org_id
     *
     * @param orgId the value for examination.org_id
     *
     * @mbggenerated
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examination.start_time
     *
     * @return the value of examination.start_time
     *
     * @mbggenerated
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examination.start_time
     *
     * @param startTime the value for examination.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime == null ? null : startTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examination.end_time
     *
     * @return the value of examination.end_time
     *
     * @mbggenerated
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examination.end_time
     *
     * @param endTime the value for examination.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime == null ? null : endTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examination.sh_people
     *
     * @return the value of examination.sh_people
     *
     * @mbggenerated
     */
    public Integer getShPeople() {
        return shPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examination.sh_people
     *
     * @param shPeople the value for examination.sh_people
     *
     * @mbggenerated
     */
    public void setShPeople(Integer shPeople) {
        this.shPeople = shPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examination.ac_people
     *
     * @return the value of examination.ac_people
     *
     * @mbggenerated
     */
    public Integer getAcPeople() {
        return acPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examination.ac_people
     *
     * @param acPeople the value for examination.ac_people
     *
     * @mbggenerated
     */
    public void setAcPeople(Integer acPeople) {
        this.acPeople = acPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examination.create_time
     *
     * @return the value of examination.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examination.create_time
     *
     * @param createTime the value for examination.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examination.founder
     *
     * @return the value of examination.founder
     *
     * @mbggenerated
     */
    public Long getFounder() {
        return founder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examination.founder
     *
     * @param founder the value for examination.founder
     *
     * @mbggenerated
     */
    public void setFounder(Long founder) {
        this.founder = founder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examination.exam_status
     *
     * @return the value of examination.exam_status
     *
     * @mbggenerated
     */
    public Integer getExamStatus() {
        return examStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examination.exam_status
     *
     * @param examStatus the value for examination.exam_status
     *
     * @mbggenerated
     */
    public void setExamStatus(Integer examStatus) {
        this.examStatus = examStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examination.attr0
     *
     * @return the value of examination.attr0
     *
     * @mbggenerated
     */
    public String getAttr0() {
        return attr0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examination.attr0
     *
     * @param attr0 the value for examination.attr0
     *
     * @mbggenerated
     */
    public void setAttr0(String attr0) {
        this.attr0 = attr0 == null ? null : attr0.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examination.attr1
     *
     * @return the value of examination.attr1
     *
     * @mbggenerated
     */
    public String getAttr1() {
        return attr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examination.attr1
     *
     * @param attr1 the value for examination.attr1
     *
     * @mbggenerated
     */
    public void setAttr1(String attr1) {
        this.attr1 = attr1 == null ? null : attr1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examination.attr2
     *
     * @return the value of examination.attr2
     *
     * @mbggenerated
     */
    public String getAttr2() {
        return attr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examination.attr2
     *
     * @param attr2 the value for examination.attr2
     *
     * @mbggenerated
     */
    public void setAttr2(String attr2) {
        this.attr2 = attr2 == null ? null : attr2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examination.attr3
     *
     * @return the value of examination.attr3
     *
     * @mbggenerated
     */
    public String getAttr3() {
        return attr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examination.attr3
     *
     * @param attr3 the value for examination.attr3
     *
     * @mbggenerated
     */
    public void setAttr3(String attr3) {
        this.attr3 = attr3 == null ? null : attr3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examination.attr4
     *
     * @return the value of examination.attr4
     *
     * @mbggenerated
     */
    public String getAttr4() {
        return attr4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examination.attr4
     *
     * @param attr4 the value for examination.attr4
     *
     * @mbggenerated
     */
    public void setAttr4(String attr4) {
        this.attr4 = attr4 == null ? null : attr4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examination.attr5
     *
     * @return the value of examination.attr5
     *
     * @mbggenerated
     */
    public String getAttr5() {
        return attr5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examination.attr5
     *
     * @param attr5 the value for examination.attr5
     *
     * @mbggenerated
     */
    public void setAttr5(String attr5) {
        this.attr5 = attr5 == null ? null : attr5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examination.attr6
     *
     * @return the value of examination.attr6
     *
     * @mbggenerated
     */
    public Integer getAttr6() {
        return attr6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examination.attr6
     *
     * @param attr6 the value for examination.attr6
     *
     * @mbggenerated
     */
    public void setAttr6(Integer attr6) {
        this.attr6 = attr6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examination.attr7
     *
     * @return the value of examination.attr7
     *
     * @mbggenerated
     */
    public Integer getAttr7() {
        return attr7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examination.attr7
     *
     * @param attr7 the value for examination.attr7
     *
     * @mbggenerated
     */
    public void setAttr7(Integer attr7) {
        this.attr7 = attr7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examination.attr8
     *
     * @return the value of examination.attr8
     *
     * @mbggenerated
     */
    public Long getAttr8() {
        return attr8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examination.attr8
     *
     * @param attr8 the value for examination.attr8
     *
     * @mbggenerated
     */
    public void setAttr8(Long attr8) {
        this.attr8 = attr8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examination.attr9
     *
     * @return the value of examination.attr9
     *
     * @mbggenerated
     */
    public Long getAttr9() {
        return attr9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examination.attr9
     *
     * @param attr9 the value for examination.attr9
     *
     * @mbggenerated
     */
    public void setAttr9(Long attr9) {
        this.attr9 = attr9;
    }
}