package cn.windy.module.examination.dao;

import cn.windy.module.examination.mybatis.model.DisRate;
import cn.windy.module.examination.mybatis.model.DisRateQuery;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface DisRateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_rate
     *
     * @mbggenerated
     */
    int countByExample(DisRateQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_rate
     *
     * @mbggenerated
     */
    int deleteByExample(DisRateQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_rate
     *
     * @mbggenerated
     */
    @Delete({
        "delete from dis_rate",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_rate
     *
     * @mbggenerated
     */
    @Insert({
        "insert into dis_rate (id, name, ",
        "type, rate_value, rate_describe, ",
        "attr0, attr1, attr2, ",
        "attr3, attr4, attr5, ",
        "attr6, attr7, attr8, ",
        "attr9)",
        "values (#{id,jdbcType=BIGINT}, #{name,jdbcType=VARCHAR}, ",
        "#{type,jdbcType=INTEGER}, #{rateValue,jdbcType=REAL}, #{rateDescribe,jdbcType=VARCHAR}, ",
        "#{attr0,jdbcType=VARCHAR}, #{attr1,jdbcType=VARCHAR}, #{attr2,jdbcType=VARCHAR}, ",
        "#{attr3,jdbcType=VARCHAR}, #{attr4,jdbcType=VARCHAR}, #{attr5,jdbcType=VARCHAR}, ",
        "#{attr6,jdbcType=VARCHAR}, #{attr7,jdbcType=VARCHAR}, #{attr8,jdbcType=VARCHAR}, ",
        "#{attr9,jdbcType=VARCHAR})"
    })
    int insert(DisRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_rate
     *
     * @mbggenerated
     */
    int insertSelective(DisRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_rate
     *
     * @mbggenerated
     */
    List<DisRate> selectByExample(DisRateQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_rate
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, name, type, rate_value, rate_describe, attr0, attr1, attr2, attr3, attr4, ",
        "attr5, attr6, attr7, attr8, attr9",
        "from dis_rate",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    DisRate selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_rate
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DisRate record, @Param("example") DisRateQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_rate
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DisRate record, @Param("example") DisRateQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_rate
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DisRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_rate
     *
     * @mbggenerated
     */
    @Update({
        "update dis_rate",
        "set name = #{name,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=INTEGER},",
          "rate_value = #{rateValue,jdbcType=REAL},",
          "rate_describe = #{rateDescribe,jdbcType=VARCHAR},",
          "attr0 = #{attr0,jdbcType=VARCHAR},",
          "attr1 = #{attr1,jdbcType=VARCHAR},",
          "attr2 = #{attr2,jdbcType=VARCHAR},",
          "attr3 = #{attr3,jdbcType=VARCHAR},",
          "attr4 = #{attr4,jdbcType=VARCHAR},",
          "attr5 = #{attr5,jdbcType=VARCHAR},",
          "attr6 = #{attr6,jdbcType=VARCHAR},",
          "attr7 = #{attr7,jdbcType=VARCHAR},",
          "attr8 = #{attr8,jdbcType=VARCHAR},",
          "attr9 = #{attr9,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(DisRate record);

    List<DisRate> findAll(@Param("start") int start,@Param("end") int end);

    List<DisRate> searchDisRateName(String name);

}